version: "3.9"
services:
    frontend:
        container_name: vue_app_container
        build:
            context: .
        volumes:
            - ./:/usr/local/app/
#            - ./src/:/usr/local/app/src/
#            - ./.env:/usr/local/app/src/.env
#            - ./package.json:/usr/local/app/package.json
            - exclude:/usr/local/app/node_modules/
        expose: [8080]
        ports:
            - "8081:8080"
#        command: bash -c "rm -rf /usr/local/app/node_modules/*"
#        command: sh -c "cp -a /node_modules/. /app/node_modules"
#        command: sh -c "rsync -avu --delete "/node_modules/" "/usr/local/app/node_modules""
volumes:
    exclude: