version: "3.9"
services:
    frontend:
        container_name: vue_app_container
        build:
            context: ./
        volumes:
            - ./:/usr/local/app
            - exclude:/usr/local/app/node_modules/
        env_file:
            - .env
        expose: [8080]
        ports:
            - "${VUE_APP_FRONTEND_PORT}:8080"
volumes:
    exclude: {}