version: "3.9"

services:
    php:
        container_name: "${DOCKER_APP_SLUG}-php-fpm"
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
            args:
                - USER_DOCKER_ID=${DOCKER_USER_ID}
                - GROUP_DOCKER_ID=${DOCKER_GROUP_ID}
                - PROJECT_PATH=${DOCKER_CODE_FOLDER}
        environment:
            APP_ENV: production
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        volumes:
            - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:${DOCKER_CODE_FOLDER}:delegated
        ports:
            - "${DOCKER_XDEBUG_PORT}:9000"
        sysctls:
            net.ipv4.ip_local_port_range: "1024 65535"
            net.ipv4.tcp_fin_timeout: "15"
            net.core.somaxconn: "65535"
        working_dir: ${DOCKER_CODE_FOLDER}
        networks:
            - backend
    nginx:
        tty: true
        image: nginx:latest
        container_name: "${DOCKER_APP_SLUG}-nginx"
        ports:
            - "${DOCKER_NGINX_PORT}:80"
            - "${DOCKER_NGINX_SSL_PORT}:443"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/ssl:/etc/nginx/ssl
            - ./:${DOCKER_CODE_FOLDER}:delegated
        depends_on:
            - php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - backend
    mysql:
        tty: true
        image: mysql:8.0
        container_name: "${DOCKER_APP_SLUG}-mysql"
        ports:
            - "${DOCKER_MYSQL_PORT}:3306"
        user: "${DOCKER_USER_ID}:${DOCKER_GROUP_ID}"
        volumes:
            - ./.docker/mysql/my.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./.docker/mysql/volumes:/var/lib/mysql:delegated
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        networks:
            - backend

    redis:
        tty: true
        image: redis:alpine
        container_name: "${DOCKER_APP_SLUG}-redis"
        ports:
            - "${DOCKER_REDIS_PORT}:6379"
        volumes:
            - ./.docker/redis/data:/data
            - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - backend

#    queue-worker:
#        build:
#            context: ./
#            dockerfile: .docker/php/Dockerfile
#            args:
#                - USER_DOCKER_ID=${DOCKER_USER_ID}
#                - GROUP_DOCKER_ID=${DOCKER_GROUP_ID}
#                - PROJECT_PATH=${DOCKER_CODE_FOLDER}
#        container_name: "${DOCKER_APP_SLUG}-queue"
#        volumes:
#            - ./:${DOCKER_CODE_FOLDER}:delegated
#            - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
#            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
#        working_dir: ${DOCKER_CODE_FOLDER}
#        command: php artisan queue:work --sleep=3 --tries=3
#        depends_on:
#            - redis
#            - mysql
#        networks:
#            - backend

networks:
    backend:
        name: backend
        driver: bridge